# Simple Linear Regression

In [1]:
import os
os.chdir("C:\\Users\\Kumar Sundram\\Desktop\\DSP35\\Python\\LR")

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import time

In [3]:
salary = pd.read_csv("Salary_Data.csv")
salary.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [4]:
# Check missing value
pd.DataFrame(salary).isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [5]:
# Store the data seperatly by Ind and Dp variable
# independent variable
x = salary.iloc[:,0:1].values
x

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [6]:
# dep variable
y = salary.iloc[:,1].values
y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [8]:
# split the data into training and test for building the model and prediction

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=100)

In [9]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(22, 1)
(8, 1)
(22,)
(8,)


In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [12]:
regressor.coef_

array([9657.22661273])

In [13]:
regressor.intercept_

25821.855048511752

In [14]:
# prediction with test dataset

y_pred = regressor.predict(x_test)
y_pred

array([ 61553.5935156 , 117565.50786941, 125291.28915959,  65416.48416069,
        53827.81222542,  64450.76149941, 118531.23053068, 112736.89456304])

In [15]:
y_test

array([ 57189., 116969., 122391.,  57081.,  56642.,  56957., 112635.,
       105582.])

In [16]:
new_salary = pd.read_excel("Salary_PRED.xlsx")
new_salary

YearsExperience
0              3.5
1             17.0
2             12.0
3              7.8
4              9.0

In [17]:
new_salary_pred = regressor.predict(new_salary)
new_salary_pred

array([ 59622.14819305, 189994.70746485, 141708.57440122, 101148.22262777,
       112736.89456304])

In [20]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9633431610802272